# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            The Milton H. Erickson Institute of Sofia
tagline:          ''
description:      'The Milton H. Erickson Institute of Sofia'
baseurl:          ''

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
